export const PLAN_LIMITS = {
  FREE: {
    SUMMARY: 10,
    FLASHCARDS: 5,
    CHAT_MESSAGES: 20,
    CHAT_CONTEXT_TOKENS: 2800, // retrieved chunks
    CHAT_HISTORY_TOKENS: 700, // conversation history
    CHAT_MAX_OUTPUT_TOKENS: 500,
  },
  STANDARD: {
    SUMMARY: 50,
    FLASHCARDS: 25,
    CHAT_MESSAGES: 100,
    CHAT_CONTEXT_TOKENS: 5800,
    CHAT_HISTORY_TOKENS: 1500,
    CHAT_MAX_OUTPUT_TOKENS: 800,
  },
  PRO: {
    SUMMARY: 100,
    FLASHCARDS: 500,
    CHAT_MESSAGES: 1000,
    CHAT_CONTEXT_TOKENS: 9000,
    CHAT_HISTORY_TOKENS: 2500,
    CHAT_MAX_OUTPUT_TOKENS: 1000,
  },
};
export const MIN_RELEVANCE_SCORE = 0.55;
